export const UsersData = [
  {
    applicationID: 'ACC20013280',
    firstname: 'Mistico',
    lastname: 'GITORE',
    email: 'misgitore@akabari.rw',
    appliedOn: '05 Jun 2022',
    decision: null,
  },
  {
    applicationID: 'ACC20011280',
    firstname: 'Icyucyi',
    lastname: 'Gishaje',
    email: 'icyugishaje@gmail.com',
    appliedOn: '06 Jun 2022',
    decision: null,
  },
  {
    applicationID: 'ACC20113284',
    firstname: 'Kmanzi',
    lastname: 'Aime',
    email: 'tunezz@gmail.com',
    appliedOn: '02 Jun 2022',
    decision: 'Shortlisted',
  },
  {
    applicationID: 'ACC20113291',
    firstname: 'Patrtick',
    lastname: 'TUNEZERWANE',
    email: 'tzz@gmail.com',
    appliedOn: '23 Aug 2022',
    decision: 'Rejected',
  },
  {
    applicationID: 'ACC20013280',
    firstname: 'Murerwa',
    lastname: 'Didi',
    email: 'tdzz@gmail.com',
    appliedOn: '05 Jun 2022',
    decision: null,
  },
  {
    applicationID: 'ACC20013280',
    firstname: 'Umwana Muto',
    lastname: 'Thia',
    email: 't@gmail.com',
    appliedOn: '05 Jun 2022',
    decision: null,
  },
  {
    applicationID: 'ACC20015280',
    firstname: 'Umukobwa',
    lastname: 'Mubi',
    email: 'mubi@gmail.com',
    appliedOn: '05 Jun 2022',
    decision: null,
  },
  {
    applicationID: 'ACC20015281',
    firstname: 'Umuhungu',
    lastname: 'Mubi',
    email: 'mubicyane@gmail.com',
    appliedOn: '05 Jun 2022',
    decision: 'Rejected',
  },
  {
    applicationID: 'ACC20015280',
    firstname: 'Umuringa',
    lastname: 'Wase',
    email: 'wase@gmail.com',
    appliedOn: '05 Jun 2022',
    decision: 'Rejected',
  },
  {
    applicationID: 'ACC20015280',
    firstname: 'IMirindi',
    lastname: 'MInini',
    email: 'mimi@gmail.com',
    appliedOn: '05 Jun 2022',
    decision: 'Shortlisted',
  },
  {
    applicationID: 'ACC20015280',
    firstname: 'UNdi',
    lastname: 'Mujama',
    email: 'undi@gmail.com',
    appliedOn: '05 Jun 2022',
    decision: 'Rejected',
  },
  {
    applicationID: 'ACC20015280',
    firstname: 'Umukobwa',
    lastname: 'Mubi',
    email: 'mubi@gmail.com',
    appliedOn: '05 Jun 2022',
    decision: null,
  },
]
